name: Build & deploy

on:
  push:
    branches:
      - release

jobs:
  build:
    name: 😵‍💫 Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🌍 Checkout code
        uses: actions/checkout@v3

      - name: 🌍 Using PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 🌍 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: 📦 Install NPM packages
        run: pnpm i

      - name: 🔧 Build project
        run: pnpm run build

      - name: 🆙 Upload to SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./dist/*"
          target: ${{ secrets.TARGET }}
          overwrite: true
          strip_components: 1